### ISSUE TITLE
Program hangs on AttributeError

### ISSUE THREAD

**Issue by aggixx** [xKynn/PathOfExileRPC#1]
When I run the exe with admin privileges after a few seconds it spits out this exception:

https://pastebin.com/DNQWbc13

After that it seems the app hangs and never succeeds in providing any rich presence info to discord.

**Comment by xKynn** [comment]
can i have your poe account name?

**Comment by aggixx** [comment]
Fearmonger

**Comment by xKynn** [comment]
Seems like your profile on poe forums isn't public, that's a requirement, i should list that

**Comment by aggixx** [comment]
Fair enough, more graceful handling of that case might be good too.

Perhaps you could circumvent requiring a public profile if the user provides a session id? Or does the character API return more information that just having a session id does not?

**Comment by xKynn** [comment]
I haven't looked into sessionid api yet, and definitely needs to be handled more gracefully

**Comment by xKynn** [comment]
Added support for POESESSID in 2c581dc62a36c02b4da772d0ffc71fb14b8a14e8 
Also added a case where on failing to get character details, user is informed of the situation and then exits
