### ISSUE TITLE
Doesn't show info about shaped maps

### ISSUE THREAD

**Issue by DaCurse** [xKynn/PathOfExileRPC#4]
I don't know if this could be implemented, but when you enter a shaped (and I also guess the same happends for elder maps) it still mentions the map's base tier

**Comment by xKynn** [comment]
That's doable I'll fix that with the new releases and some more things I've
recently added, thanks

**Comment by xKynn** [comment]
Not possible, logs don't reveal if an entered map was shaped etc.
